language: android

android:
    components:
        - platform-tools
        - tools
        # BuildTools version used
        - build-tools-23.0.3

        # SDK version used to compile the project
        - android-23

        # Additional components
        - extra-google-m2repository
        - extra-android-m2repository

    licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

script:
    - ./gradlew build
